# Generated by Django 4.2.6 on 2023-10-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRestApp', '0002_alter_review_movie_alter_review_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='MovieRestApp.ratingstar', verbose_name='Звезда'),
        ),
    ]
