# Generated by Django 4.2.6 on 2023-10-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRestApp', '0005_alter_rating_movie_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='MovieRestApp.ratingstar', verbose_name='Звезда'),
        ),
    ]
