# Generated by Django 4.2.6 on 2023-10-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRestApp', '0006_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='MovieRestApp.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieRestApp.ratingstar', verbose_name='Звезда'),
        ),
    ]
